Repository netlify/eslint-config-node, pull requests merged in 2020-12, with the labels that each got.

#33 fix(linting): remove `no-return-await` rule
  .eslintrc.js
Labels: type: bug

#34 chore(publish): add publish script to git push version change and tag
  package.json
Labels: type: chore

#41 Add `no-unsafe-optional-chaining` ESLint rule
  .eslintrc.js
Labels: type: chore

#43 Add `prefer-arrow-callback` ESLint rule
  .eslintrc.js
Labels: type: chore

#42 Add `arrow-body-style` ESLint rule
  .eslintrc.js
Labels: type: chore

#44 Update `README.md` outdated information
  README.md
Labels: type: chore

#45 Add `429` to `no-magic-numbers`
  .eslintrc.js
Labels: type: chore

#46 Allow magic numbers in `README.md`
  .eslintrc.js
Labels: type: chore

#52 chore: add commit linting
  commitlint.config.js
  package-lock.json
  package.json
Labels: type: chore

#53 feat: document commit linting
  README.md
  package-lock.json
  package.json
Labels: type: feature

#54 chore: add release PR flow
  .github/workflows/release-please.yml
  CONTRIBUTING.md
  package.json
Labels: type: chore

#57 feat: add browser configs
  README.md
  react_config.js
  vanilla_js_config.js
Labels: type: feature

#59 fix: add missing linting configurations
  package.json
Labels: type: bug

#61 fix(eslint-react): disable unicorn/import-index
  react_config.js
Labels: type: bug
