Repository netlify/eslint-config-node, pull requests merged in 2021-06, with the labels that each got.

#217 feat: add more status codes to `no-magic-numbers`
  .eslintrc.js
  package-lock.json
  package.json
Labels: type: chore, type: feature

#228 fix(linting): disable prefer-prototype-methods
  .eslintrc.js
Labels: type: bug

#244 chore(ci): prelease action
  .github/workflows/pre-release.yml
  CONTRIBUTING.md
Labels: type: chore
