Repository netlify/eslint-config-node, pull requests merged in 2021-05, with the labels that each got.

#182 fix: disable unicorn flat and flatmap rules
  .eslintrc.js
Labels: type: bug

#189 fix: import/extensions rule
  .eslintrc.js
Labels: type: bug, type: chore

#191 chore: fix importing JSON files
  .eslintrc.js
Labels: type: chore

#193 fix: remove file-extension-in-import
  .eslintrc.js
Labels: type: bug

#195 chore: run CI on latest Node.js
  .github/workflows/release-please.yml
  .github/workflows/workflow.yml
  test/main.js
Labels: type: chore

#197 chore: remove dead code
  test/main.js
Labels: type: chore

#200 chore: fix test coverage upload
  .github/workflows/workflow.yml
Labels: type: chore

#206 fix: make functional programming linting opt-in
  .eslintrc.js
Labels: type: chore
