Repository netlify/eslint-config-node, pull requests merged in 2021-02, with the labels that each got.

#97 chore: support Node 15
  .github/workflows/workflow.yml
  package.json
Labels: type: chore

#102 chore: fix linting and formatting on npm@7
  README.md
  package.json
Labels: type: chore

#110 fix: add husky to readme
  README.md
Labels: type: bug

#112 feat: update markdown code blocks rules
  .eslintrc.js
Labels: type: feature

#114 chore: fix linting imports in Markdown files
  .eslintrc.js
Labels: type: chore
