Repository netlify/eslint-config-node, pull requests merged in 2022-01, with the labels that each got.

#395 fix: disable no-await-in-loop
  .eslintrc.js
Labels: type: bug, automerge

#402 chore: clean up npm files section
  package.json
Labels: type: chore, automerge

#398 fix: fix scripts to run on Windows
  package.json
Labels: type: chore

#401 fix(deps): downgrade eslint-plugin-promise to v5.2.0
  package-lock.json
  package.json
Labels: type: bug, automerge

#410 chore: remove coverage since it's unused on this repo
  .github/workflows/workflow.yml
  .gitignore
  codecov.yml
  package-lock.json
  package.json
Labels: type: chore

#397 feat: Enable a few more newer Node.js rules
  .eslintrc.js
Labels: type: feature, automerge

#403 fix(deps): update husky package to the latest
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  README.md
  package-lock.json
  package.json
Labels: type: feature

#415 fix: `commitlint` Git hook
  .husky/commit-msg
Labels: type: bug

#414 chore: remove `pre-commit` hook
  .husky/pre-commit
Labels: type: chore, automerge

#413 fix: make Git hooks executable
  .husky/commit-msg
  .husky/pre-push
Labels: type: bug, automerge

#417 fix: add `npx` to `commitlint`
  .husky/commit-msg
Labels: type: bug

#423 fix: inline `eslint-plugin-unicorn` recommended rules
  .eslintrc.js
Labels: type: chore, automerge

#427 fix: remove broken duplicate rule
  .eslintrc.js
Labels: type: bug, automerge
